apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: health-leaf-classifier-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: health-leaf-classifier-deployment
  minReplicas: 1
  maxReplicas: 5 # Adjusted to 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60 # Added cpu scaling
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70 # Added memory scaling
